services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    working_dir: "/app"
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'
    networks: 
      - "chat-network"
    tty: true
    command: make
    depends_on:
      - "db"
  db:
    image: postgres:17.0-alpine
    ports:
      - '15432:5432'
    networks: 
      - "chat-network"
    volumes:
      - chat-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'pg-user'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DATABASE: 'chat_database'
volumes:
  chat-volume:
networks:
  chat-network:
